---
- name: Install k8s packages
  become: true
  pacman:
    name:
      - docker
      - docker-machine
      - libvirt
      - qemu-headless
      - ebtables
      - dnsmasq

- name: start services
  become: true
  systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  loop:
    - libvirtd
    - virtlogd

- name: install kvm2 driver
  become: true
  become_user: aur_builder
  aur:
    skip_installed: true
    name: "{{ item }}"
  loop:
    - docker-machine-driver-kvm2
    - minikube-bin
    - kubectl-bin

- name: add users to libvirt group
  become: true
  user:
    name: eric
    append: true
    groups: libvirt

- command: "minikube status"
  register: minikube_status
  ignore_errors: true

- name: start minikube
  shell: "minikube start --vm-driver kvm2"
  when: minikube_status is failed
