- name: clone doom to ~/src/doom-emacs
  git:
    repo: https://github.com/hlissner/doom-emacs
    dest: ~/src/doom-emacs
- name: rm ~/.emacs
  file:
    path: ~/.emacs
    state: absent
- name: symlink ~/.emacs.d to ~/src/doom-emacs
  file:
    path: ~/.emacs.d
    state: link
    src: ~/src/doom-emacs
- name: symlink ~/.doom.d to ~/dotfiles/.doom.d
  file:
    path: ~/.doom.d
    state: link
    src: ~/dotfiles/doom.d
- name: tools
  become: true
  pacman:
    name: '{{ item }}'
    state: present
  loop:
  - shellcheck
  - ripgrep
  - the_silver_searcher
  when: ansible_facts['os_family'] == 'Manjaro'
- name: tools
  homebrew:
    name: '{{ item }}'
    state: present
  when: ansible_facts['os_family'] == 'Darwin'
  loop:
  - aspell
  - the_silver_searcher
  - ripgrep
- name: refresh env
  command: ~/src/doom-emacs/bin/doom -y env refresh
- name: refresh doom
  command: ~/src/doom-emacs/bin/doom -y refresh
