---
golang_tarball_url: https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz
golang_tarball_checksum: sha256:aea86e3c73495f205929cfebba0d63f1382c8ac59be081b6351681415f4063cf 
golang_tarball_path: /usr/local/src
golang_path: /opt
golang_path_manage: true
golang_remove: false
golang_packages:
  - github.com/mdempsky/gocode
  - github.com/rogpeppe/godef
  - golang.org/x/tools/cmd/guru
  - golang.org/x/tools/cmd/gorename
  - golang.org/x/tools/cmd/goimports
  - golang.org/x/tools/cmd/godoc
  - github.com/zmb3/gogetdoc
  - github.com/cweill/gotests/...
  - github.com/haya14busa/gopkgs/cmd/gopkgs
  - github.com/davidrjenni/reftools/cmd/fillstruct
  - github.com/josharian/impl
  - github.com/golangci/golangci-lint/cmd/golangci-lint
