---
- name: install fonts
  pacman:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - nerd-fonts-noto-sans-mono 
    - noto-fonts-emoji
    - otf-fira-code
    - ttf-fira-code
    - otf-fira-mono
    - ttf-fira-mono

- name: install AUR fonts
  become: true
  become_user: aur_builder
  aur:
    skip_installed: true
    name: "{{ item }}"
  loop:
    - ttf-monoid
